###########################
##      MSCPO Website      ##
##Classification DataBase  ##
##     Format: Yaml        ##
##    Language: en      ##
###########################

- title: Survival server
  items:
    - title: OPCraft
      icon: /server_icons/DFGG_Logo.webp
      desc: A server where everyone without rules has administrator rights
      link: https://op.dfggmc.top/

- title: Creative server
  items:
    - title: FLMP Server
      icon: /server_icons/DFGG_Logo.webp
      desc: Minecraft: Java version 1.21 creative architecture-based server
      link: https://dfggmc.top/
    - title: OPCraft
      icon: /server_icons/DFGG_Logo.webp
      desc: A server where everyone without rules has administrator rights
      link: https://op.dfggmc.top/

- title: PvP server
  items:
    - title: Not yet
      icon: /logo.webp
      link: https://mscpo.top

- title: Mini game server
  items:
    - title: Not yet
      icon: /logo.webp
      link: https://mscpo.top/

- title: Other servers
  items:
    - title: OPCraft
      icon: /server_icons/DFGG_Logo.webp
      desc: A server where everyone without rules has administrator rights
      link: https://op.dfggmc.top/
