name: Servers Request
on:
  issues:
    types:
      - labeled

jobs:
  get-server-info:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Submit'
    permissions:
      issues: read
    timeout-minutes: 2
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: PSModule/Get-IssueFormData@v0
      - name: Organize Inputs
        id: organize-inputs
        run: |
          echo ${{ toJSON(steps.parse.outputs.data) }} | jq '
