###########################
##      MSCPO Website    ##
##  Navigation DataBase  ##
##     Format: Yaml      ##
##    Language: zh_CN    ##
###########################

# Type: Official_Website
# 图像索引: Official_Website
- title: Official Website
  items:
    - title: Minecraft官网
      icon: /Nav_Images/Official_Website/Minecraft.webp
      desc: 欢迎来到 Minecraft 的官方网站，在这里您可以下载 Windows、Mac 和 Linux 版的 Minecraft。
      link: https://www.minecraft.net/
    - title: 教育版官网
      icon: /Nav_Images/Official_Website/Minecraft_Education.webp
      desc: Minecraft教育版（Minecraft Education）是Minecraft特别为教室使用而设计的教学版本。
      link: https://education.minecraft.net/
    - title: Minecraft中国版
      icon: /Nav_Images/Official_Website/mc.163.com.webp
      link: https://mc.163.com/
    - title: Minecraft Feedback
      icon: /Nav_Images/Official_Website/Minecraft_Feedback.webp
      desc: Minecraft的官方反馈社区
      link: https://feedback.minecraft.net/
    - title: Mojang Jira
      icon: /Nav_Images/Official_Website/Mojang_Jira.webp
      desc: Minecraft的官方BUG反馈社区
      link: https://bugs.mojang.com/projects/MC/issues
    - title: FindMCServer
      icon: /Nav_Images/Official_Website/FindMCServer.webp
      desc: 官方Minecraft服务器列表
      link: https://findmcserver.com/
    - title: Minecraft Classic
      icon: /Nav_Images/Official_Website/Minecraft_Feedback.webp
      desc: Minecraft Classic是著名的开放世界沙盒构建游戏Minecraft的在线版本。
      link: https://classic.minecraft.net/
    - title: 网易版论坛
      icon: /Nav_Images/Official_Website/mc.163.com.webp
      desc: 中国版官方论坛
      link: https://mc.netease.com/

# 分类: 百科
# 图像索引: Wiki_Class
- title: Wiki
  items:
    - title: 中文 Minecraft Wiki
      icon: '/Nav_Images/Wiki_Class/Minecraft_Wiki.webp'
      desc: Minecraft最著名的、最权威的非官方百科网站
      link: 'https://minecraft.wiki/'
    - title: DigMinecraft
      icon: '/Nav_Images/Wiki_Class/DigMinecraft.webp'
      desc: 一个英文MC百科网站
      link: 'https://www.digminecraft.com/'
    - title: Wiki.vg
      icon: '/Nav_Images/Wiki_Class/Wiki.vg.webp'
      desc: 英文的Minecraft开发文档库
      link: 'https://wiki.vg/'
    - title: MC模组百科
      icon: '/Nav_Images/Wiki_Class/MCMod.CN.webp'
      desc: 国内很著名的MC模组百科网站
      link: 'https://www.mcmod.cn/'
    - title: Minecraft 插件百科
      icon: '/Nav_Images/Wiki_Class/Minecraft_Plugin_Wiki.webp'
      desc: 一个中文MC插件百科网站
      link: 'https://mineplugin.org/'
    - title: Minecraft Parkour Wiki
      icon: '/Nav_Images/Wiki_Class/Minecraft_Parkour_Wiki.webp'
      desc: 这是一个记录 Minecraft 跑酷知识以及玩家运动机制的 wiki。
      link: https://www.mcpk.wiki/
    - title: 笨蛋 MC 开服教程
      icon: '/Nav_Images/Wiki_Class/NitWikit.webp'
      desc: MC开服教程
      link: 'https://yizhan.wiki/NitWikit/'

# 分类: 非官方论坛
# 图像索引: Unofficial_BBS
- title: Unofficial BBS
  items:
    - title: Minecraft Forum
      icon: /Nav_Images/Unofficial_BBS/Minecraft_Forum.webp
      desc: 国外比较有名的非官方Minecraft论坛
      link: https://www.minecraftforum.net/
    - title: MineBBS
      icon: /Nav_Images/Unofficial_BBS/MineBBS.webp
      desc: 一个国内的我的世界中文论坛，主营基岩版
      link: https://www.minebbs.com/
    - title: 苦力怕论坛
      icon: /Nav_Images/Unofficial_BBS/KLPBBS.webp
      desc: 国内的我的世界中文论坛，主营基岩版
      link: https://klpbbs.com/
    - title: Bangbang93论坛
      icon: /Nav_Images/Unofficial_BBS/Bangbang93BBS.webp
      desc: 十分著名的下载源国内镜像站——BMCLAPI
      link: https://www.bangbang93.com
    - title: MCBBS纪念版
      icon: /Nav_Images/Unofficial_BBS/MCBBS2.webp
      desc: 人能够能动地认识世界；人能够能动地改造世界。
      link: https://mcbbs2.net/
    - title: Minecraft教育版论坛
      icon: /Nav_Images/Official_Website/Minecraft_Education.webp
      desc: 教育版基于基岩版制作，包含了可以在课堂里让Minecraft更易理解和更有效果的特性。
      link: https://www.mceebbs.com/
    - title: Minecraft吧
      icon: /Nav_Images/Unofficial_BBS/MinecraftBaidu.webp
      desc: 百度贴吧Minecraft吧，一个活跃的第三方玩家社区。
      link: https://tieba.baidu.com/f?kw=minecraft
    - title: Minecraft-HK Community
      icon: /Nav_Images/Unofficial_BBS/Minecraft-HK.webp
      desc: 交流有關 Minecraft 的最新資訊、專業教學、遊戲伺服器、相關資源及心得分享
      link: https://www.minecraft-hk.com/
    - title: MCPE-TW
      icon: /Nav_Images/Unofficial_BBS/MCPE-TW.webp
      desc: 來自中國台灣的 Minecraft PE 中文討論區
      link: https://www.minecraft-hk.com/
    - title: 我的世界小黑论坛
      icon: /Nav_Images/Unofficial_BBS/Minecraft_BL-PineApple BBS.webp
      desc: 來自中國台灣的 Minecraft PE 中文討論區
      link: https://www.minecraft-hk.com/

# 分类: 基岩版开发文档
# 图像索引: Bedrock_DEV_Docs
- title: Bedrock DEV Docs
  items:
    - title: MC基岩版开发Wiki
      icon: '/Nav_Images/Bedrock_DEV_Docs/MCBE-Dev.svg'
      link: 'https://wiki.mcbe-dev.net/'
    - title: Bedrock Wiki
      icon: '/Nav_Images/Bedrock_DEV_Docs/Bedrock_Wiki.webp'
      link: 'https://wiki.bedrock.dev'
    - title: bedrock.dev
      icon: '/Nav_Images/Bedrock_DEV_Docs/bedrock.dev.webp'
      link: 'https://bedrock.dev/'

# 分类: 资源站
# 图像索引: Resource_Website
- title: Resource Website
  items:
    - title: MCVersions
      icon: '/Nav_Images/Resource_Website/MCVersions.svg'
      desc: Java版各版本jar下载
      link: 'https://mcversions.net/'
    - title: Minecraft for Android 版本库
      icon: '/Nav_Images/Resource_Website/Minecraft for Android 版本库.webp'
      desc: 安卓基岩版下载
      link: 'https://bbk.endyun.ltd/'
    - title: Minecraft for Windows 版本库
      icon: '/Nav_Images/Resource_Website/Minecraft for Windows 版本库.webp'
      desc: PC基岩版下载
      link: 'https://www.mcappx.com/'
    - title: CurseForge
      icon: '/Nav_Images/Resource_Website/CurseForge.webp'
      desc: 老牌MC资源站
      link: 'https://www.curseforge.com/minecraft'
    - title: Modrinth
      icon: '/Nav_Images/Resource_Website/Modrinth.webp'
      desc: 新兴的Minecraft第三方资源站
      link: 'https://modrinth.com'
    - title: PlanetMinecraft
      icon: '/Nav_Images/Resource_Website/PlanetMinecraft.webp'
      desc: 著名的Minecraft资源网站
      link: 'https://www.planetminecraft.com/'
    - title: SpigotMC
      icon: '/Nav_Images/Resource_Website/SpigotMc.webp'
      desc: 提供许多插件的SpigotMc资源板块
      link: 'https://www.spigotmc.org/resources/'
    - title: Hanger
      icon: '/Nav_Images/Resource_Website/Hanger.svg'
      desc: PaperMC提供的插件站
      link: 'https://hangar.papermc.io/'
    - title: Sponge Ore
      icon: '/Nav_Images/Resource_Website/Sponge Ore.webp'
      desc: Sponge服务端插件下载站
      link: 'https://ore.spongepowered.org/'
    - title: MCPEDL
      icon: '/Nav_Images/Resource_Website/MCPEDL.webp'
      desc: 专注基岩版资源的网站
      link: 'https://mcpedl.com/'
    - title: MinecraftYard
      icon: '/Nav_Images/Resource_Website/MinecraftYard.webp'
      desc: 收录了Java版的一些资源
      link: 'https://www.minecraftyard.com/'
    - title: Minecraft Mods
      icon: '/Nav_Images/Resource_Website/Minecraft Mods.webp'
      desc: '收录了一些Java版的模组资源'
      link: 'https://www.minecraftmods.com/'
    - title: Minecraft Maps
      icon: '/Nav_Images/Resource_Website/Minecraft Maps.webp'
      desc: '一个MC游戏地图的专门资源网站'
      link: 'https://www.minecraftmaps.com/'
    - title: Minecraft Shaders
      icon: '/Nav_Images/Resource_Website/Minecraft_Shaders.webp'
      desc: '提供MC的光影包和资源包资源'
      link: 'https://minecraftshader.com/'
    - title: 'Resourse Packs for Minecraft'
      icon: '/Nav_Images/Resource_Website/Resourse Packs for Minecraft.webp'
      desc: '主要提供MC的各种资源包资源'
      link: 'https://resourcepack.net/'
    - title: LittleSkin
      icon: /Nav_Images/Resource_Website/LittleSkin.webp
      desc: 国内老牌MC皮肤站
      link: https://littleskin.cn/
    - title: Minecraft Skins
      icon: /Nav_Images/Resource_Website/MinecraftSkins.webp
      desc: 一个英文的MC皮肤资源网站
      link: https://www.minecraftskins.com/
    - title: MSkins
      icon: /Nav_Images/Resource_Website/MSkins.webp
      desc: 一个英文的MC皮肤资源网站
      link: https://mskins.net/
    - title: Minecraft Sounds
      icon: /Nav_Images/Resource_Website/Minecraft_Sounds.webp
      desc: 一个国内MC音效下载网站
      link: https://o.xbottle.top/mcsounds/
    - title: Minecraft Schematics
      icon: /Nav_Images/Resource_Website/Minecraft_Schematics.webp
      desc: 此站收纳了大量用户上传的Minecraft Schematic文件（创世神模组用的结构文件），亦可用于投影模组（Litematica）
      link: https://www.minecraft-schematics.com/
    - title: Minecraft Schematics
      icon: /Nav_Images/Resource_Website/MCserver.webp
      desc: 我的世界综合性网站，为服主提供各种服务器教程、插件、MOD、软件资源，建站服务。为MC玩家展示服务器，提供教程。
      link: https://www.mcio.cn/
    - title: Modpack Index
      icon: /Nav_Images/Resource_Website/ModpackIndex.webp
      desc: Modpack Index 是作为实用程序构建的，以帮助跟踪惊人的不断增长的 Modpack 社区。
      link: https://www.modpackindex.com/
    - title: Minecraft Polska
      icon: /Nav_Images/Resource_Website/Minecraft_Polska.webp
      desc: minecraft.org.pl 是一个关于 Minecraft 的波兰网站，您可以在其中找到有关游戏、模组、纹理和游戏其他附加内容的新闻。
      link: https://minecraft.org.pl/
    - title: Block Models
      icon: /Nav_Images/Official_Website/Minecraft_Feedback.webp
      desc: BlockModels.com是一个你可以上传，分享和推广你的Minecraft方块模型的网站。
      link: https://blockmodels.com/
    - title: TITAIKE
      icon: /Nav_Images/Resource_Website/TITAIKE.webp
      desc: TITAIKE是国内一家整合及翻译国内外基岩版地图的网站，在整合优质国外基岩版地图的前提下，我们也接收来自国内各大工作室及个人的作品
      link: https://www.titaike.cn/
    - title: MinecraftCapes
      icon: /Nav_Images/Resource_Website/MinecraftCapes.webp
      desc: 免费披风斗篷站 - 在游戏中穿任何你想要的斗篷和披风
      link: https://minecraftcapes.net/

# 分类: 服务器门户
# 图像索引: Server_Gateway
- title: Server Gateway
  items:
    - title: Minecraft Servers
      icon: /Nav_Images/Server_Gateway/Minecraft Servers.webp
      desc: 国外比较著名的服务器资源网站
      link: https://minecraftservers.org/
    - title: Minecraft Multiplayer
      icon: /Nav_Images/Server_Gateway/Minecraft Multiplayer.webp
      desc: 国外比较著名的服务器资源网站
      link: https://minecraft-mp.com/
    - title: 我的世界找服网
      icon: /Nav_Images/Server_Gateway/我的世界找服网.webp
      desc: 一个国内的服务器资源网站
      link: https://www.mczfw.cn/
    - title: Minecraft服务器列表
      icon: /Nav_Images/Server_Gateway/Minecraft服务器列表.webp
      desc: 一个国内的服务器资源网站
      link: https://www.mczfw.cn/
    - title: MCMOD服务器列表
      icon: /Nav_Images/Server_Gateway/MCMOD服务器列表.webp
      desc: MCMOD服务器板块
      link: https://play.mcmod.cn/
    - title: 服务器集体宣传组织
      icon: /logo2.webp
      desc: 服务器集体宣传组织(MSCPO)官方网站
      link: https://mscpo.netlify.app/
    - title: MCJPG组织
      icon: /Nav_Images/Server_Gateway/MCJPG.webp
      desc: MCJPG组织官网
      link: https://mcjpg.org

# 分类: 功能性网站
# 图像索引: Functional_website
- title: Functional website
  items:
    - title: Chunk Base
      icon: /Nav_Images/Functional_website/Chunk Base.webp
      desc: 种子查询器、区块查询器等工具网站
      link: https://www.chunkbase.com/
    - title: Minecraft Tools
      icon: /Nav_Images/Functional_website/Minecraft Tools.webp
      desc: 提供各种自定义等工具
      link: https://minecraft.tools/
    - title: Minecraft Server Tools
      icon: /Nav_Images/Functional_website/Minecraft Server Tools.webp
      desc: 提供各种自定义服务器的工具
      link: https://mctools.org/
    - title: Minecraft Server Status
      icon: /Nav_Images/Functional_website/Minecraft Server Status.webp
      desc: 网页MC服务器状态检测
      link: https://mcsrvstat.us/
    - title: MCS
      icon: /Nav_Images/Functional_website/MCS.webp
      desc: 网页MC服务器状态检测
      link: https://mcstatus.io/
    - title: mclo.gs
      icon: /Nav_Images/Functional_website/mclo.gs.webp
      desc: MC服务器日志分析
      link: https://mclo.gs/
    - title: Reden
      icon: /Nav_Images/Functional_website/Reden.webp
      desc: 世吞等投影文件在线生成
      link: https://redenmc.com/
    - title: MapartCraft
      icon: /Nav_Images/Functional_website/MapartCraft.webp
      desc: MC像素画生成器,支持投影
      link: https://rebane2001.com/mapartcraft/zh-Hans
    - title: Minecraft PFP
      icon: /Nav_Images/Functional_website/Minecraft PFP.webp
      desc: 根据正版账号皮肤生成头像
      link: https://www.minecraftpfp.com/
    - title: GAMEGEEKS
      icon: /Nav_Images/Functional_website/GAMEGEEKS.webp
      desc: 网页MC指令生成
      link: https://www.gamergeeks.net/
    - title: Nova Skin
      icon: /Nav_Images/Functional_website/Nova Skin.webp
      desc: 网页MC皮肤站,可以制作、上传皮肤和下载皮肤的壁纸
      link: https://minecraft.novaskin.me/
    - title: MC-3D皮肤预览
      icon: /Nav_Images/Functional_website/MC-3D皮肤预览.webp
      desc: MC皮肤查询、3D预览
      link: https://skin.endyun.ltd/
    - title: Textcraft
      icon: /Nav_Images/Functional_website/Textcraft.webp
      desc: 生成MC风格的各种艺术字
      link: https://textcraft.net/
    - title: Chunker
      icon: /Nav_Images/Functional_website/Chunker.webp
      desc: 在线MC跨版本地图转换器,支持JE和BE互转
      link: https://chunker.app/
    - title: Minecraft Heads
      icon: /Nav_Images/Functional_website/Minecraft Heads.webp
      desc: "收集了大量MC装饰性头颅 "
      link: https://www.minecraft-heads.com/
    - title: Minecraft Shapes
      icon: /Nav_Images/Functional_website/Minecraft Shapes.webp
      desc: 指导在MC搭建规范的图形
      link: https://minecraftshapes.com/
    - title: NameMC
      icon: /Nav_Images/Functional_website/NameMC.webp
      desc: 查询正版玩家皮肤、名称、皮肤、UUID等信息
      link: https://zh-cn.namemc.com/
    - title: Minecraft UUID
      icon: /Nav_Images/Functional_website/Minecraft UUID.webp
      desc: 查询正版玩家的UUID等信息
      link: https://mcuuid.net/

# 分类: 模组和光影加载器
# 图像索引: Light_and_Shadow_Loader
- title: Light and Shadow Loader
  items:
    - title: Forge
      icon: /Nav_Images/Light_and_Shadow_Loader/Forge.webp
      desc: 老牌模组加载器官网
      link: https://forums.minecraftforge.net/
    - title: NeoForge
      icon: /Nav_Images/Light_and_Shadow_Loader/NeoForge.webp
      desc: Forge在高版本的更佳分支
      link: https://neoforged.net/
    - title: Fabric
      icon: /Nav_Images/Light_and_Shadow_Loader/Fabric.webp
      desc: 新兴热门模组加载器
      link: https://fabricmc.net/
    - title: Quilt
      icon: /Nav_Images/Light_and_Shadow_Loader/Quilt.webp
      desc: Fabric下游分支
      link: https://quiltmc.org/en/
    - title: LiteLoader
      icon: /Nav_Images/Light_and_Shadow_Loader/LiteLoader.webp
      desc: 轻量级模组加载器,较久没更新
      link: http://www.liteloader.com/
    - title: Optifine
      icon: /Nav_Images/Light_and_Shadow_Loader/Optifine.webp
      desc: 老牌渲染优化模组高清修复,也可作为光影加载器
      link: https://www.optifine.net
    - title: Iris Shaders
      icon: /Nav_Images/Light_and_Shadow_Loader/Iris Shaders.webp
      desc: 通过Fabric驱动的Java版高版本光影加载器,与钠兼容
      link: https://irisshaders.net/

# 分类: 启动器和客户端
# 图像索引: Client
- title: Client
  items:
    - title: Minecraft 官方启动器
      icon: /Nav_Images/Official_Website/Minecraft.webp
      desc: MC官方启动器
      link: https://www.minecraft.net/zh-hans/download
    - title: HMCL
      icon: /Nav_Images/Client/HMCL.webp
      desc: 经典老牌启动器,跨平台
      link: https://hmcl.huangyuhui.net/
    - title: PCL2
      icon: /Nav_Images/Client/PCL2.webp
      desc: 新兴启动器,适于新手
      link: https://afdian.com/p/0164034c016c11ebafcb52540025c377
    - title: BakaXL
      icon: /Nav_Images/Client/BakaXL.webp
      desc: 国产二次元启动器.界面美观
      link: https://www.bakaxl.com/
    - title: MultiMC
      icon: /Nav_Images/Client/MultiMC.webp
      desc: 国外老牌启动器,支持中文
      link: https://multimc.org/
    - title: 中国版启动器
      icon: /Nav_Images/Official_Website/mc.163.com.webp
      desc: 中国版官网
      link: https://mc.163.com/
    - title: Lunar Client
      icon: /Nav_Images/Client/Lunar Client.webp
      desc: 热门PVP客户端
      link: https://www.lunarclient.com/
    - title: Badlion Client
      icon: /Nav_Images/Client/Badlion Client.webp
      desc: 热门PVP客户端
      link: https://client.badlion.net/zh-CN
    - title: Labymod
      icon: /Nav_Images/Client/LabyMod.svg
      desc: 热门PVP客户端
      link: https://labymod.net/zh_Hans
    - title: FEATHER CLIENT
      icon: /Nav_Images/Client/FEATHER CLIENT.webp
      desc: 热门PVP客户端
      link: https://feathermc.com/

# 分类: 实用软件
# 图像索引: Practical_Software
- title: Practical Software
  items:
    - title: EaglerCraft
      icon: /Nav_Images/Practical_Software/EaglerCraft.webp
      desc: EaglercraftX 网页版MC,版本JE1.8.8
      link: https://eaglercraft.ru/
    - title: MCC
      icon: /Nav_Images/Practical_Software/MCC.webp
      desc: MC命令行客户端
      link: https://mccteam.github.io/l10n/zh-Hans/
    - title: MCA Selector
      icon: /Nav_Images/Practical_Software/MCA Selector.webp
      desc: MC区块选择器,方便编辑区块,支持中文
      link: https://github.com/Querz/mcaselector
